apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-dashboard
  template:
    metadata:
      labels:
        app: kubernetes-dashboard
    spec:
      containers:
      - name: kubernetes-dashboard
        image: kubernetes-dashboard:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-dashboard-service
spec:
  selector:
    app: kubernetes-dashboard
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: NodePort
